name: CI

on: push

jobs:
  rpmlin:
    name: rpmlint
    runs-on: ubuntu-24.04
    container: fedora:44
    steps:
    - uses: actions/checkout@v5
    - name: Install rpmlint
      run: dnf install -y rpmlint
    - name: rpmlint
      run: rpmlint specs/ --strict
